name: Java CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'what version of java are you using?'
        type: string
        default: '11'
        required: false
      app-name:
        description: 'put your application name here'
        default: dtn-test
        type: string
        required: true
      app-version:
        description: 'here for version of your application'
        default: 0.0.1
        type: string
        required: true
    secrets:
      project-id:
        required: true
      gcloud-key:
         required: true
    
jobs:
  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: permission mvnw
        run: chmod +x ./mvnw
      - name: Build Quarkus Native
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker
        # Push To Artifactory
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.project-id }}
          service_account_key: ${{ secrets.gcloud-key }}
          export_default_credentials: true
      - name: Login and configure gcloud for docker
        run: gcloud --quiet auth configure-docker
        shell: bash
      - name: Build Docker Image
        run: |
          docker build -f src/main/docker/Dockerfile.native -t asia-southeast2-docker.pkg.dev/dtn-utility/dtn-container-registry/${{ inputs.app-name }}:${{ inputs.app-version }} . \
          && docker push asia-southeast2-docker.pkg.dev/dtn-utility/dtn-container-registry/${{ inputs.app-name }}:${{ inputs.app-version }}
        shell: bash
      
 
    

